###Mengambar persamaan bidang dalam ruang 3 dimensi

#Penyelesaian sistem linier

Penyelesaian sistem Persamaan linier dengan menggunakan gausin

Pertama kita selesaikan persamaan berikut:

$$
8x_1+x_2+x_3=19\\
x_1+2x_2+3x_3=9\\
2x_1+x_2-x_3=5\\
$$

Berikut penyelesaian dari persaman diatas

In [1]:
import numpy as np
A=np.array([[8,9,1,19],[1,2,3,9],[2,1,1,5]])
print(A)

[[ 8  9  1 19]
 [ 1  2  3  9]
 [ 2  1  1  5]]


###Mendefinisikan fungsi operasi baris eliminasi GAUSS

* RowSwap() => Berfungsi unutuk menukar posisi persamaan

* RowScale() => Berfungsi untuk mengkalikan persamaan dengan skala

* RowAdd() => Berfungsi untuk menambahkan persamaan yang salah satunya sudah dikalikan dengan skala

In [2]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped. (menukarkan persamaan)
# =============================================================================
    m = A.shape[0]  # m is number of rows in A (jumlah baris A)
    n = A.shape[1]  # n is number of columns in A (jumlah kolom A)

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale. (mengalikan entry baris A dengan skala)
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modified.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale. (menambahkan nilai baris k dikalikan dengan skala)
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

Tahapan penyelesaian dengan menggunakan Eliminasi Gauss

In [3]:
# Print Soal
print(A)
print("\n")

## Tukar baris 0 dengan 1
A1 = RowSwap(A,0,1)
print(A1,'\n')

## Tambahkan -8 kali baris 0 ke baris 1
A2 = RowAdd(A1,0,1,-8)
print(A2,'\n')

## Tambahkan -2 kali baris 0 ke baris 2
A3 = RowAdd(A2,0,2,-2)
print(A3,'\n')

## Kalikan baris 2 dengan -7
A4 = RowScale(A3,2,-7)
print(A4,'\n')

## Tambahkan 3 kali baris 1 ke baris 2
A5 = RowAdd(A4,1,2,3)
print(A5)

## Kalikan baris 2 dengan -1/34
A6 = RowScale(A5,2,-1/34)
print(A6)

## Kalikan baris 1 dengan -1/7
A7 = RowScale(A6,1,-1/7)
print(A7)

[[ 8  9  1 19]
 [ 1  2  3  9]
 [ 2  1  1  5]]


[[ 1.  2.  3.  9.]
 [ 8.  9.  1. 19.]
 [ 2.  1.  1.  5.]] 

[[  1.   2.   3.   9.]
 [  0.  -7. -23. -53.]
 [  2.   1.   1.   5.]] 

[[  1.   2.   3.   9.]
 [  0.  -7. -23. -53.]
 [  0.  -3.  -5. -13.]] 

[[  1.   2.   3.   9.]
 [  0.  -7. -23. -53.]
 [ -0.  21.  35.  91.]] 

[[  1.   2.   3.   9.]
 [  0.  -7. -23. -53.]
 [  0.   0. -34. -68.]]
[[  1.   2.   3.   9.]
 [  0.  -7. -23. -53.]
 [ -0.  -0.   1.   2.]]
[[ 1.          2.          3.          9.        ]
 [-0.          1.          3.28571429  7.57142857]
 [-0.         -0.          1.          2.        ]]
